### ISSUE TITLE
Add tap support?

### ISSUE THREAD

**Issue by StarkITA** [Gabisonfire/dashboard-q#17]
It would be nice to add a tap support, so the dashboard would be useful from tablet as well.

From my research, it needs jquery mobile.

**Comment by Gabisonfire** [comment]
I like the idea but I'm not comfortable enough with jQuery to consider doing something like that unfortunately.

**Comment by StarkITA** [comment]
I can give it a try in the following days (as soon as I have time, a scarce and rare commodity...).

If I make progress I'll update here. I really like the idea of this project.

**Comment by StarkITA** [comment]
So... After a bit of digging and testing, looks like my test subject prevented me to open into a iframe.

This made all of my testing useless, since tapping WORKS.

Sorry.

PEBKAC.
