### ISSUE TITLE
Feature Request - Sub sections for Bookmarks

### ISSUE THREAD

**Issue by darkcloud784** [Gabisonfire/dashboard-q#4]
Adding collapsible sub sections to bookmarks would make it much easier to keep some dashboards organized. example:

Media
     --Plex
     --Plexpy
Automation
      --Couchpotato
      --Sonarr
      --FlexGet

**Comment by Gabisonfire** [comment]
Good idea, will work on it.

**Comment by Gabisonfire** [comment]
@Digital-Storm If you wanna take a look at this, be my guest :)

I will try to make it happen but I'm not familiar with jQuery enough. I can handle the php side though as I was thinking about making a bookmark page just like the settings.

**Comment by darkcloud784** [comment]
@Gabisonfire @Digital-Storm 
I actually really like the idea of a bookmark page. It would just improve the ease of use.

**Comment by Gabisonfire** [comment]
Took me only a year, better late than never :)

https://github.com/Gabisonfire/dashboard-q/commit/6c5d6756bd96c5445c4c7f7f51e1a445ff5454e1
