### ISSUE TITLE
Gap between navigation bar and main page

### ISSUE THREAD

**Issue by Gabisonfire** [Gabisonfire/dashboard-q#8]
There is a gap between the navigation bar and the main page. It loads slightly after the page has loaded so I'm assuming its an issue with the JS. Could you take a look @Digital-Storm since I'm terrible with JS.

Thanks!

![gap](https://cloud.githubusercontent.com/assets/6416239/18025573/acda3fa8-6bfb-11e6-927b-f4a80c2f4fc3.png)

**Comment by Digital-Storm** [comment]
I'll take a look into this.

**Comment by Gabisonfire** [comment]
has to do with this
    		jQuery('#theframe').addClass('sidebar-closed');
                jQuery('#sidebar > ul').hide();
		jQuery('#theframe').css({
                    //'width': 'calc(100% - 180px)'
                    'width': '100%',
                    'margin-left': '0px'

**Comment by Gabisonfire** [comment]
Not the best fix but it does the job https://github.com/Gabisonfire/dashboard-q/commit/040cd1861e97549a9475a9d9d59da2a77dcac4d4

Just need to make the iframe resize when toggling the bar.

**Comment by Digital-Storm** [comment]
See pull request #11. That should resolve this without the scripts.js modification.

**Comment by Gabisonfire** [comment]
Yea that fixed it. Thanks!
